import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import { Marko_One} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

//const inter = Inter({ subsets: ["latin"] });
const markoOne= Marko_One({ subsets: ["latin"], weight: ['400'] });

export const metadata: Metadata = {
  title: "Klove",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const markoOneClass = markoOne.className
  return (
    <html lang="en">
      <body className={`${markoOneClass} my-16 mx-12 bg-[#110515]`} >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
